### ISSUE TITLE
GitHub repo description and repo link

### ISSUE THREAD

**Issue by szepeviktor** [spamhaus/rbldnsd#14]
Please consider adding GitHub repo description and repo link
Missing here: https://github.com/spamhaus/rbldnsd

**Comment by ammammita** [comment]
Done.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Could you add https://rbldnsd.io/ as "Website"?

**Comment by ammammita** [comment]
Thanks for pointing out. I was sure i added it but i was wrong.
Done.
