### ISSUE TITLE
Base Template documentation incorrect

### ISSUE THREAD

**Issue by nottledim** [spamhaus/rbldnsd#18]
The man page for this program is incorrect in that the Base Template is not defined as quoted below.  It is defined as:
`$= See http://www.example.com/bl?$= ($) for details`

Quote:
`      If the "base template" ($= variable) is defined, this template is used
       for expansion, instead of the one specified for an entry being
       queried.  Inside the base template, $= construct is substituted with
       the text given for individual entries. In order to stop usage of base
       template $= for a single record, start it with = (which will be
       omitted from the resulting TXT value).  For example,

         $0 See http://www.example.com/bl?$= ($) for details
         127.0.0.2    r123
         127.0.0.3
         127.0.0.4    =See other blocklists for details about $`

Whilst you're at it: this sentence is unclear:
`There is no default TXT value, so rbldnsd will not return anything for TXT queries it TXT isn't specified.`
I think it means `There is no default TXT value, so rbldnsd will not return anything for TXT queries unless TXT is specified`  but I'm not sure.

**Comment by ammammita** [comment]
Thanks for pointing it out, i've edited the manual file and pushed to the `ticket-18-and-19` a revised version.

I'll merge to master with the other fix for the bug you found regarding the template.
