### ISSUE TITLE
Base Template substitution error

### ISSUE THREAD

**Issue by nottledim** [spamhaus/rbldnsd#19]
With base template:

`$= See http://www.example.com/bl?$= ($) for details`

The TXT for the entry is substituted correctly for `$=` but the substitution for `$` instead of being the IP address of entry is the same text as `$=`.

**Comment by ammammita** [comment]
I think that this bug has been there for ages. Thanks for spotting it.
A fix has been pushed to the `ticket-18-and-19` branch. 

If you confirm that it's fixed, then i'll merge to master.
